name: Deploy comic pages
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ "16.x" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install packages
        run: npm install
      - name: registry github user
        run: |
          git config --global user.email danielvasquez@protonmail.com
          git config --global user.name DanielVZA
      - name: deploy the app
        run: npm run deploy
        env:
          GH_PAGES: ${{secrets.GH_PAGES}}
